# Generated by Django 3.2 on 2021-04-26 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_rename_images_postimage_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postimage',
            name='image',
        ),
        migrations.AddField(
            model_name='postimage',
            name='images',
            field=models.ImageField(blank=True, upload_to='media/'),
        ),
    ]
