# Generated by Django 3.2 on 2021-04-29 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auto_20210426_2047'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postimage',
            name='default',
        ),
    ]
