# Generated by Django 3.2 on 2021-04-13 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_rename_product_id_watchlist_product_key'),
    ]

    operations = [
        migrations.RenameField(
            model_name='watchlist',
            old_name='product_key',
            new_name='product_id',
        ),
    ]
